# SQL Interview Questions  - Quiz

## Introduction

In this lesson, we'll go through a short quiz containing the types of questions about SQL and relational databases that you can expect to see in an interview. 



## SQL Interview Questions

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

what are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line:
_______________________________________________________________________________________________________________________________
Text - string types
Integer - numeric
Real - something with a decimal up to 15 characters long
Blob - see the data exactly how it was entered




## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
_______________________________________________________________________________________________________________________________

Every table needs at least one primary key. There can be multiple. They uniquely identify a row.
Foreign keys are non-primary key fields in the table in which you are working but are primary keys in another table that can be used to join the two tables.



## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
One-to-one: each row in the primary table only corresponds to one or no rows in the related table.
One-to-many: each row in the primary key table corresponds to none, one, or many rows in the related table. E.g. parent to children.
Many-to-many: each record in the primary key table corresponds to none to any number of rows in the related table. E.g. siblings to siblings.



## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
Inner Join: only the rows from the primary table that have a match in the related table.
Left Join: all records from the pt joined to any matching rows on the rt. Rt can have blank fields.
Right Join: all records from the rt joined to any matching rows on the pt. Pt can have blank fields.
Full Outer Join: all records from both pt and rt. Both pt and rt could then have blank fields
There are also iterations of the joins where you could remove the pt or rt rows that don't have matching records by calling a WHERE statement to the Join (WHERE A.key IS NULL)


## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
AFs will initially start with the full data set e.g. SUM(totalRevenue) would return one row with the sum of the full totalRevenue column. Use Group By to set a parameter by which the AF will opperate. E.g. SUM(totalRevenue) GROUP BY region would return X rows for the X regions in the dataset and the sum of revenue by region.




## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:
_______________________________________________________________________________________________________________________________
A relational db requires the use of a base relation or base table to solve many-to-many relationships. This established base table can also be called an associative table. These ATs maps two or more tables together by referencing the primary keys from both tables


## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.